server:
  servlet:
    context-path: /murphy

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/murphy
    username: murphy
    password: xxxxxxxxxxxxxxxxx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: xxxxxxxxxxxxxxxxx
            clientSecret: xxxxxxxxxxxxxxxxx
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret:xxxxxxxxxxxxxxxxx
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/murphy/user/me
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
